version: 2

machine:
  java:
    version: 11

general:
  branches:
    only:
      - master # list of branches to build

jobs:
#  build:
#    docker:
#      - image: circleci/openjdk:11-jdk
#      - image: circleci/node:jessie-browsers
    steps:
      # clone repository
      - checkout
      - run:
          name: install chrome browser
          command: sudo apt-get install libxss1 libappindicator1 libindicator7
                   && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                   && sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb
                   && sudo apt-get install -f
      - run:
          name: run sut in background
          command: java -jar artifacts/app-callback.jar &
      - run:
          name: give permission for ./gradlew
          command: chmod +x ./gradlew
      - run:
          name: run tests
          command: ./gradlew test -Dselenium.headless=true