# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      # clone repository
      - checkout
      - run:
          name: install chrome browser
          command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
                   && dpkg -i --force-depends google-chrome-stable_current_amd64.deb
      - run:
          name: run sut in background
          command: java -jar artifacts/app-callback.jar &
      - run:
          name: give permission for ./gradlew
          command: chmod +x ./gradlew
      - run:
          name: run tests
          command: ./gradlew test -Dselenium.headless=true

