# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - name: install chrome browser
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: dpkg -i --force-depends google-chrome-stable_current_amd64.deb
      - name: clone repository
      - checkout
      - name: run sut in background
      - run: java -jar artifacts/app-callback.jar &
      - name: give permission for ./gradlew and run tests
      - run: chmod +x ./gradlew
      - run: ./gradlew test -Dselenium.headless=true
