version: 2

jobs:
  build:
    docker:
      #use jdk image with browsers
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      #clone repository
      - checkout
      - run:
          name: run sut in background
          command: java -jar artifacts/app-callback.jar
          background: true
      - run:
          name: wait sut running
          command: sleep 5
      - run:
          name: give permission for ./gradlew
          command: chmod +x ./gradlew
      - run:
          name: run tests
          command: ./gradlew test --info